### ISSUE TITLE
有些安卓手机生成后没有定位点

### ISSUE THREAD

**Issue by Mfweb** [yingye/weapp-qrcode#12]
测试了华为几款手机，定位点缺失

**Comment by yingye** [comment]
麻烦把代码和问题截图贴一下呗

**Comment by Mfweb** [comment]
我按照#9 的方式解决了这个问题，但是没有进行大量测试；
希望能直接设置添加边框。

**Comment by yingye** [comment]
还是麻烦详细描述一下问题，#9 的问题最终定位在使用上，并不是 sdk 本身问题。
【希望能直接设置添加边框。】这是另一个需求吗？

**Comment by Mfweb** [comment]
我目前是生成一个二维码，然后复制二维码部分到另一个已经绘制好边框到canvas中，我到问题和#9 是一样到，绘制完成后在回调中立即获取像素就会出现定位点问题，现在加了300ms延时再复制就没有发现问题。
【希望能直接设置添加边框。】这是另一个需求，希望能设置二维码在canvas中绘制到区域，这样可以先绘制好边框或者其他到，然后在中间部分绘制二维码

**Comment by yingye** [comment]
【绘制完成后在回调中立即获取像素就会出现定位点问题】获取像素是？是否方便贴一下代码？

**Comment by yingye** [comment]
【希望能直接设置添加边框。】通过设置父级标签可以实现该功能，比如设置父级的padding或者margin值。

**Comment by Mfweb** [comment]
例如使用wx.canvasGetImageData获取，就会就会出现定位点缺失，如果在callback中延时300ms再使用wx.canvasGetImageData获取，就不会出现这个问题；另外这个问题只会在某些安卓手机上出现，iOS暂时没有发现；这个问题和#9 应该是一样到。

【希望能直接设置添加边框。】如果通过父级标签当用户选择保存二维码时比较麻烦，还是倾向是否可以设置二维码绘制区域，预先绘制好边框再在制定区域绘制二维码。

**Comment by yingye** [comment]
延时300ms，是可以解决问题的吧？该问题应该是安卓微信小程序的问题。
【希望能直接设置添加边框】该问题可以再建一个 issue 来处理，之前没有考虑到保存二维码的情况

**Comment by ixiaoq** [comment]
`// 生成二维码, 并转换为 image
    createQrCode (qrUrl) {
        console.log(qrUrl);
        drawQrcode({
            x: 10,
            y: 10,
            width: 170,
            height: 170,
            canvasId: 'myQrcode',
            text: qrUrl,
            callback: () => {

                // canvas 转 image
                wx.canvasToTempFilePath({
                    x: 0,
                    y: 0,
                    width: 180,
                    height: 180,
                    canvasId: 'myQrcode',
                    success: res => {
                        this.setData({
                            qrcode_img: res.tempFilePath
                        });
                    }
                });

            }
           
        });
    }`
问题：没有定位点
生成二维码后，获取临时地址 images 展示

**Comment by ixiaoq** [comment]
`function createQrCode (qrUrl) {
        drawQrcode({
            x: 10,
            y: 10,
            width: 170,
            height: 170,
            canvasId: 'myQrcode',
            text: qrUrl,
            callback: () => {
                wx.canvasToTempFilePath({
                    x: 0,
                    y: 0,
                    width: 180,
                    height: 180,
                    canvasId: 'myQrcode',
                    success: res => {
                        this.setData({
                            qrcode_img: res.tempFilePath
                        });
                    }
                });
            }           
        });
    }`
![微信图片_20190710151149](https://user-images.githubusercontent.com/23451031/60948268-20262900-a325-11e9-8c3a-87d45559893f.png)

问题：没有定位点
生成二维码后，获取临时地址 images 展示
