### ISSUE TITLE
三星 Galaxy S7 微信6.7.2的版本上二维码生成不全

### ISSUE THREAD

**Issue by fwlong** [yingye/weapp-qrcode#16]
右边和下边超出了边界

**Comment by yingye** [comment]
麻烦贴一下截图 和 必要的代码，帮助定位问题，谢谢～

**Comment by roy-yi** [comment]
![image](https://user-images.githubusercontent.com/19289298/49625125-34ace680-fa0f-11e8-8835-782e4367013e.png)
这个二维码就生成不全

**Comment by roy-yi** [comment]
`drawQrcode({
        width: 150,
        height: 150,
        canvasId: 'qrcode',
        // typeNumber: 8,
        correctLevel: 0,
        text: shareUrl,
        callback: e => {
          console.log(e)
          wx.canvasToTempFilePath({ // 将canvas中的图片保存到手机临时目录
            canvasId: 'qrcode',
            x: 0,
            y: 0,
            width: 150,
            height: 150,
            destWidth: 150,
            destHeight: 150,
            success(qr) { // 保存成功回调，回调参数qr为保存的图片信息
              const ctx = wx.createCanvasContext('qrcode')
              ctx.drawImage('../assets/static/img/index/poster.png', 0, 0, 420, 550) // 画背景海报
              ctx.fillStyle = '#FFFFFF'
              ctx.fillRect(129, 208, 158, 158) // 填充整个背景底色
              ctx.drawImage(qr.tempFilePath, 133, 212, 150, 150) // 画二维码
              ctx.drawImage('../assets/static/img/cmcc_logo.png', 194, 272, 30, 30) // 在二维码中间画logo

              ctx.drawImage('../assets/static/img/cmcc_logo.png', 45, 30, 60, 60) // 画合伙人LOGO
              // ---> 绘制合伙人昵称、合伙人电话、资费分享标题的文字
              canvasTextAutoWrap(that.currentShareFee.packageName, ctx, 130, 57, 300, 24, 2, (20) + 'px 黑体', '#000000')
              // canvasTextAutoWrap(that.phoneShow, ctx, 130, 85, 400, 16, 1, (16) + 'px 黑体', '#777777')
              canvasTextAutoWrap(that.currentShareFee.packageBrief, ctx, 115, 139, 300, 24, 2, (20) + 'px 黑体', '#333333')
              // <---
              ctx.stroke()
              ctx.draw(false, function() {
                console.log('绘制完成')
                wx.canvasToTempFilePath({
                  canvasId: 'qrcode',
                  x: 0,
                  y: 0,
                  width: 420,
                  height: 550,
                  destWidth: 420 * 3,
                  destHeight: 550 * 3,
                  success(poster) {
                    console.log(poster)
                    that.posterSrc = poster.tempFilePath
                    tip.loaded()
                    that.qrcodeShow = true
                    that.$apply()
                  }
                })
              })
            }
          })
        }
      })`

**Comment by roy-yi** [comment]
在所有的安卓手机上都不行

**Comment by yingye** [comment]
分步调试一下呗，看一下 “// 将canvas中的图片保存到手机临时目录”  这一步生成的二维码是否有问题～

**Comment by roy-yi** [comment]
我发现问题了，我如果直接用保存的临时二维码，这个二维码是正确的；但是我把临时保存的二维码再画到canvas上的时候，二维码就乱了。
求教：怎么在二维码中间画logo

**Comment by yingye** [comment]
v1.0.0版本开始支持在二维码上绘制图片～
