### ISSUE TITLE
第二次生成二维码空白，微信小程序

### ISSUE THREAD

**Issue by boy-good** [yingye/weapp-qrcode#19]
使用在微信小程序上
第一次可以生成二维码
但是我把弹框关闭后再次打开就空白了
![image](https://user-images.githubusercontent.com/39320533/47868738-fafd2480-de3f-11e8-9a61-6c99beaca376.png)
![image](https://user-images.githubusercontent.com/39320533/47868752-02bcc900-de40-11e8-8ded-91a0f7ce77e1.png)

**Comment by yingye** [comment]
放在哪个生命周期里执行的该方法啊？

**Comment by boy-good** [comment]
@yingye 我知道原因了，是因为我的弹窗使用了 wx:if 渲染，第一次弹窗可以渲染，但之后重新渲染就画不了二维码了，后来我改成 hidden 方式就可以。是不是和画布渲染有关呢？

**Comment by yingye** [comment]
在调用 drawQrcode()方法之前，一定要确保可以获取到 canvas context
