### ISSUE TITLE
建议添加在Taro框架下的使用说明

### ISSUE THREAD

**Issue by Barretem** [yingye/weapp-qrcode#23]
该库在Taro（v1.0.2）框架下可以使用，只是使用的时候必须要注意以下两点：

1. drawQrcode方法的调用建议在componentDidMount的生命周期;
2. 在drawQrcode方法中，_this参数为必填项，应该赋值为this.$scope

具体操作：

1. 引入Canvas组件
`import { Canvas } from '@tarojs/components';`
2. 在组件中使用Canvas组件
`                <Canvas style='width: 200px; height: 200px;' canvasId='myQrcode' />
`
3. 在ComponentDidMount组件中加入以下方法
`drawQrcode({
      width: 200,
      height: 200,
      canvasId: 'myQrcode',
      _this: this.$scope,
      text: 'https://github.com/yingye'
    });`

谢大佬！！

**Comment by yingye** [comment]
@Barretem 是否有兴趣写一个简单的demo，添加到该 repo examples 目录下？

**Comment by Barretem** [comment]
@yingye 好的，我最近写一下一个简单的demo

**Comment by fancyhejianyang** [comment]
3.0 以后无this.$scope，建议补充完整demo

**Comment by lalawow** [comment]
新版的Taro下可以用 `Taro.getCurrentInstance().page` 替代 `this.$scope`.
https://github.com/NervJS/taro/issues/7795
