### ISSUE TITLE
二维码上的图片能否支持自定义样式

### ISSUE THREAD

**Issue by fml077** [yingye/weapp-qrcode#29]
![image](https://user-images.githubusercontent.com/23355182/51302785-59649700-1a6e-11e9-80bc-134f43526615.png)

比如这个二维码上的红色图片本来是方形的，想添加border-radius添加圆角效果，不知可以支持吗？目前暴露的image接口只看到这5个
{imageResource: '../../images/icon.png',
    dx: 70,
    dy: 70,
    dWidth: 60,
    dHeight: 60}

**Comment by yingye** [comment]
这里是在 canvas 上绘制图片，和 css 添加 border-radius 属性不一样哈。目前版本还不支持圆角。

**Comment by fml077** [comment]
额 好吧……
