### ISSUE TITLE
rpx为单位的时候出现尺寸不统一的问题

### ISSUE THREAD

**Issue by Realzzz1874** [yingye/weapp-qrcode#3]
## rpx为单位的时候出现尺寸不统一的问题
`<canvas class="can" style="" canvas-id="ticket_qrcode"></canvas>`

```
.can{
  width: 320rpx;
  height: 320rpx;
}
```
```
    drawQrcode({
      width: 320,
      height: 320,
      canvasId: 'ticket_qrcode',
      text: this.ticket_order,
    });
```

在drawQrcode中，width和height填写320是错误的，但是填写160就是正常的，填写160在模拟器上的样式是正常的，但是手机上查看就会变成160的大小。

**Comment by yingye** [comment]
建议使用 px 定义 canvas 的宽高，具体可参考 [小程序·画布](https://mp.weixin.qq.com/debug/wxadoc/dev/component/canvas.html#canvas)

**Comment by Realzzz1874** [comment]
rpx更好做适配吧，使用px的话如何适应不同机型呢

**Comment by yingye** [comment]
可以使用js做转换，例如：
```js
let clientWidth = wx.getSystemInfoSync().screenWidth;
let canvasWidth = Math.floor(clientWidth * 160 / 750);
```
