### ISSUE TITLE
是不是自定义组件中无法使用

### ISSUE THREAD

**Issue by Latter321** [yingye/weapp-qrcode#31]
所有参数都给的静态，其余步骤按文档来做的，只是二维码被放到了自定义组件中，但是发现没有报错，二维码显示不出来。是否不支持自定义组件中使用？
试过在使用组件的页面中onLoad或者onReady中就调用drawQrcode来绘制自定义组件中的二维码，但是还是没用。

**Comment by savokiss** [comment]
自定义组件中需要传 _this，可以看 #18 中贴的代码
