### ISSUE TITLE
如何设置 x, y 区域(二维码边框)的颜色？

### ISSUE THREAD

**Issue by Houserqu** [yingye/weapp-qrcode#33]
如题，默认是透明的，通过canvasToTempFilePath生成图片再预览的时候，四周都是黑色，会出现扫码失败的情况。

**Comment by yingye** [comment]
因为在绘制二维码时，可以传入绘图上下文 `ctx`，所以可以在传入 `ctx` 之前，绘制 `canvas` 背景色。
```js
var ctx = wx.createCanvasContext('myQrcode')
ctx.save()
ctx.setFillStyle('red')
ctx.fillRect(0, 0, 200, 200)
ctx.restore()
// 传入 ctx，绘制二维码
this.draw(ctx)
```

**Comment by Houserqu** [comment]
嗯嗯，目前是这么解决的，如果能够通过配置项实现的话，会更方便一点。

**Comment by youyou12344** [comment]
> 因为在绘制二维码时，可以传入绘图上下文 `ctx`，所以可以在传入 `ctx` 之前，绘制 `canvas` 背景色。
> 
> ```js
> var ctx = wx.createCanvasContext('myQrcode')
> ctx.save()
> ctx.setFillStyle('red')
> ctx.fillRect(0, 0, 200, 200)
> ctx.restore()
> // 传入 ctx，绘制二维码
> this.draw(ctx)
> ```

下载的最新版本weapp.qrcode.esm.js，ctx失效了。
我看到代码里面写了，draw(!1, ...)
即，不保留上次的绘画结果。
