### ISSUE TITLE
生成的二维码在iphone xs max 和iphone x上 二维码变形

### ISSUE THREAD

**Issue by dafuchixigua** [yingye/weapp-qrcode#35]
![TIM图片20190410092807](https://user-images.githubusercontent.com/42792604/55845089-fec16f80-5b72-11e9-9426-50a1c07e8879.png)

**Comment by yingye** [comment]
我用example里面的代码，在上述两款机型上试了一下，没有发现问题。
麻烦贴一下必要的代码吧。 @dafuchixigua

**Comment by dafuchixigua** [comment]
不好意思是没问题的。。。我自己使用错误。




------------------ 原始邮件 ------------------
发件人: "yingye"<notifications@github.com>;
发送时间: 2019年5月20日(星期一) 上午10:25
收件人: "yingye/weapp-qrcode"<weapp-qrcode@noreply.github.com>;
抄送: "暮　西　米"<295085981@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [yingye/weapp-qrcode] 生成的二维码在iphone xs max 和iphone x上 二维码变形 (#35)




我用example里面的代码，在上述两款机型上试了一下，没有发现问题。
 麻烦贴一下必要的代码吧。 @dafuchixigua
