### ISSUE TITLE
回调中清除了画布，第二次点击还是出现空白

### ISSUE THREAD

**Issue by xiaojia90s** [yingye/weapp-qrcode#39]
回调中清除了画布，第二次点击还是出现空白，怎么回事？还有就是如何确保拿到canvas context

**Comment by yingye** [comment]
请详细描述问题，尽量按照issue模版填写，提供必要代码，谢谢

**Comment by xiaojia90s** [comment]
就是我点击某个按钮，按照文档生成二维码，然后点击遮罩层二维码消失之后，再点击这个按钮，这个二维码就不会再出现，但是遮罩层会出来，然后审查元素会看到有canvas元素存在，却没有看到有回调输出


------------------ 原始邮件 ------------------
发件人: "yingye"<notifications@github.com>;
发送时间: 2019年6月5日(星期三) 上午10:42
收件人: "yingye/weapp-qrcode"<weapp-qrcode@noreply.github.com>;
抄送: "随性"<981461889@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [yingye/weapp-qrcode] 回调中清除了画布，第二次点击还是出现空白 (#39)




请详细描述问题，尽量按照issue模版填写，提供必要代码，谢谢

**Comment by yingye** [comment]
贴代码，谢谢。根据你的描述，我无法定位问题。

**Comment by xiaojia90s** [comment]
稍后，谢谢你的回复、


------------------ 原始邮件 ------------------
发件人: "yingye"<notifications@github.com>;
发送时间: 2019年6月5日(星期三) 上午10:49
收件人: "yingye/weapp-qrcode"<weapp-qrcode@noreply.github.com>;
抄送: "随性"<981461889@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [yingye/weapp-qrcode] 回调中清除了画布，第二次点击还是出现空白 (#39)




贴代码，谢谢。根据你的描述，我无法定位问题。
