### ISSUE TITLE
能否将CanvasContext.draw()方法的reserve参数（第一个参数）暴露出来

### ISSUE THREAD

**Issue by Dio-Zhu** [yingye/weapp-qrcode#42]
# Description

[问题简单描述]
现有代码里面的reserve参数是写死的false
    ctx.draw(false, function (e) {
      options.callback && options.callback(e);
    });
类似海报图片的绘制：
步骤1.在canvas中绘制大量其它内容
步骤2.然后再留一小块区域绘制二维码
因为 你们把reserve参数写死为false，导致绘制二维码时把步骤1中绘制的内容全部清除了。

[在这里描述期望的表现]
希望能把 reserve 参数暴露出来可由外部传递，默认值为false即可。

**Comment by justrustc** [comment]
+1

**Comment by 179778978** [comment]
我将node_modules下的weapp.qrcode.js文件拷贝出来，把reserve参数修改了一下，当成静态文件放到项目里了，这样也是可以的，上传时候小程序会自动压缩代码

**Comment by chenjinya** [comment]
https://github.com/yingye/weapp-qrcode/pull/73

提交了 PR，加了 `draw` 参数

**Comment by alfredzh** [comment]
为什么close了？
