### ISSUE TITLE
绘制图片时，开发者工具显示都正常。真机调试只能显示本地图片，无法显示在线图片

### ISSUE THREAD

**Issue by rkrv01** [yingye/weapp-qrcode#43]

**Comment by xzifan** [comment]
同情况

**Comment by yingye** [comment]
网络图片要通过 getImageInfo / downloadFile 先下载！
参考：[CanvasContext.drawImage](https://developers.weixin.qq.com/miniprogram/dev/api/canvas/CanvasContext.drawImage.html)
