### ISSUE TITLE
drawQrcode不支持在components中使用

### ISSUE THREAD

**Issue by czl0325** [yingye/weapp-qrcode#44]
drawQrcode不支持在components中使用

只能在pages中使用！！！

**Comment by yingye** [comment]
请参考 [examples/wechat-app](https://github.com/yingye/weapp-qrcode/tree/master/examples/wechat-app)
如果还不能使用，请按照 issue 模版，详细描述问题～

**Comment by da-sha** [comment]
components中加上 _this: this 选项就好了,
