### ISSUE TITLE
怎么将生成的二维码保存为本地图片。

### ISSUE THREAD

**Issue by Ucself** [yingye/weapp-qrcode#47]
# Description

[问题简单描述]

# Environment

* Platform: [开发者工具/iOS/Andriod/Web]
* Platform version: [对应工具或者iOS或者Andriod的版本号]
* Wechat version: [微信版本号]
* weapp-qrcode version: [在package.json里]
* other version: [如果在某一设备下出现该问题，请填写设备号]

# Reproduce

**问题复现步骤:**
怎么将生成的二维码保存为本地图片。
**期望的表现:**

[在这里描述期望的表现]

怎么将生成的二维码保存为本地图片。

[在这里描述观察到的表现]

怎么将生成的二维码保存为本地图片。

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)

# Relevant Code / Logs

```
// TODO(you): code or logs here to reproduce the problem
```

**Comment by Noizx** [comment]
相关讨论 #40

**Comment by ibobjoy** [comment]
drawQrcode({
          width: 300-40, height: 300-40,
          x: 20, y: 20,
          canvasId: 'canvas',
          background: '#ffffff',
          foreground: '#000000',
          text: "sample text",
          callback(e) {
            console.log('e: ', e)
            //callback 回调不准确 #18
            setTimeout(() => {
              wx.canvasToTempFilePath({
                x: 0,
                y: 0,
                width: 300,
                height: 300,
                canvasId: 'canvas',
                fileType: 'png',
                success(res) {
                  console.log('图片的临时路径为：', res.tempFilePath)
                  let tempFilePath = res.tempFilePath
                  that.setData({
                    qrImgsrc: tempFilePath,
                    shareTips: "长按图片，直接分享给微信好友",
                    qrLoaded:true
                  })
                }
              })
            }, 500)

          }
        })
