### ISSUE TITLE
链接长度过长，二维码生成报错，怎么解决？

### ISSUE THREAD

**Issue by ZhangWren** [yingye/weapp-qrcode#49]
# Description

要生成二维码的链接过长，二维码生成失败，报错

# Environment

* Platform: [开发者工具/iOS/Andriod/Web]
* Platform version: [对应工具或者iOS或者Andriod的版本号]
* Wechat version: [微信版本号]
* weapp-qrcode version: [在package.json里]
* other version: [如果在某一设备下出现该问题，请填写设备号]

# Reproduce

**问题复现步骤:**

1. [第一步]
2. [第二步]
3. [其他步骤...]

**期望的表现:**

[在这里描述期望的表现]

**观察到的表现:**

[在这里描述观察到的表现]

**屏幕截图和动态 GIF 图**

![1569230237](https://user-images.githubusercontent.com/25240164/65414318-070e1e00-de26-11e9-8a8f-f9bf192b47fd.png)

# Relevant Code / Logs

```
// TODO(you): code or logs here to reproduce the problem
```

**Comment by yingye** [comment]
尝试一下，降低纠错等级
