### ISSUE TITLE
生成的Canvas层级太高，不能通过css来更改输入后的样式，有什么好的解决方法么

### ISSUE THREAD

**Issue by Niubility-SunLight** [yingye/weapp-qrcode#50]
生成的Canvas层级太高，不能通过css来更改输入后的样式，有什么好的解决方法么

**Comment by yingye** [comment]
该问题与微信小程序渲染机制有关，sdk 无法解决该问题～

**Comment by gaotongjian** [comment]
可以考虑使用`wx.canvasToTempFilePath`和`wx.getImageInfo` api转成图片来渲染。
