### ISSUE TITLE
使用0.6.0版本在开发环境可以很好的显示qrcode，真机和远程调试的时候显示不出来

### ISSUE THREAD

**Issue by rj03hou** [yingye/weapp-qrcode#6]
你好，rt
<view class="container">
    <scroll-view class="wrapper-scroll" scroll-y="true"  bindscrolltoupper="upper" bindscrolltolower="lower" bindscroll="scroll" scroll-top="100">
        <canvas class='canvas'  canvas-id='canvas' bindlongtap='saveqrcode' wx:if="{{directfrom == 'mybook'}}"></canvas>
    </scroll-view>
</view>

代码里面定义了
function setQrcode(that){
    drawQrcode({
      width: 150,
      height: 150,
      canvasId: 'canvas',
      text: qrcodetext,
      correctLevel: 1 
    })
}
}
在onload里面调用了setQrcode
wxss文件里面定义了样式
.canvas {
    margin: 80rpx auto;
    width: 150px;
    height: 150px;
    /* border: 1px solid black; */
}

问题：在微信开发者工具里面显示没有问题，但是到了真机和远程调试的时候显示不出来，真机显示闪了一下二维码，但是页面没有

**Comment by yingye** [comment]
onload生命周期，渲染还没有完成，参考 [注册页面·小程序](https://developers.weixin.qq.com/miniprogram/dev/framework/app-service/page.html)

**Comment by rj03hou** [comment]
放在onshow里面会好一些？

**Comment by guandaxia** [comment]
我遇到的情况是部分机型显示不出来

**Comment by yingye** [comment]
@guandaxia 可以详细描述一下问题么？哪部分机型显示不出来，方便的话贴一下调用方法的代码。

**Comment by guandaxia** [comment]
@yingye 手机型号是华为C199，微信版本是6.6.7

![image](https://user-images.githubusercontent.com/9638813/40897428-a7f98044-67ed-11e8-9c22-99c61b90990e.png)
调用是放在onShow函数里的

**Comment by beysong** [comment]
onShow里面还要延迟300ms才行
