### ISSUE TITLE
华为 nova 5i Pro 二维码出不来

### ISSUE THREAD

**Issue by webpig** [yingye/weapp-qrcode#65]
# Description

华为 nova 5i Pro 二维码出不来

# Environment

* Platform: [Andriod]
* Platform version: [Andriod 9，EMUI版本9.1.1]
* Wechat version: [7.0.13]
* weapp-qrcode version: [^1.0.0]
* other version: [华为 nova 5i Pro]

问题截图：

![image](https://user-images.githubusercontent.com/24989439/80554556-24c8e480-8a00-11ea-89e1-26c26dbce28c.png)

**Comment by webpig** [comment]
延迟生成

**Comment by ChenCaiquan** [comment]
其他机型能否正常显示?

**Comment by ChenCaiquan** [comment]
> 延迟生成
其他机型是否正常生成？ ？   模拟器中呢

**Comment by webpig** [comment]
目前都正常，没碰到问题，

**Comment by webpig** [comment]
> > 延迟生成
> > 其他机型是否正常生成？ ？   模拟器中呢

目前都正常，没碰到问题，
